quarkus.datasource.db-kind=PostgreSQL
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

%dev.quarkus.datasource.reactive.url=postgresql://localhost:5432/iot

quarkus.http.port=8080

smallrye.jwt.new-token.signature-algorithm=RS256
smallrye.jwt.sign.key.location=${SECRETS_DIR:../secrets}/jwt/private.pem

jwt.key.id=Hkn7Yqe8yC8XAJHiEJPmDqBqMfoDzPhgid691GNEgSw
auth.jwt.issuer=auth-service

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=false

# METRICS
quarkus.otel.metrics.enabled=true
quarkus.otel.exporter.otlp.metrics.endpoint=http://localhost:4317/v1/metrics
quarkus.otel.metric.export.interval=30s
