quarkus.http.port=8081

smallrye.jwt.new-token.signature-algorithm=RS256
smallrye.jwt.sign.key.location=${SECRETS_DIR:../secrets}/jwt/private.pem
quarkus.config.locations=${SECRETS_DIR:../secrets}/admin/credentials.properties

jwt.key.id=Hkn7Yqe8yC8XAJHiEJPmDqBqMfoDzPhgid691GNEgSw
auth.jwt.issuer=auth-service

# REST
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true

# METRICS
quarkus.otel.metrics.enabled=true
quarkus.datasource.metrics.enabled=true

quarkus.otel.exporter.otlp.metrics.endpoint=http://localhost:4317/v1/metrics
quarkus.otel.metric.export.interval=10s

# BASIC AUTH
quarkus.http.auth.basic=true

# DATABASE
quarkus.datasource.db-kind=PostgreSQL
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.reactive.max-size=40

# TODO dev.quarkus.hibernate-orm.schema-management.strategy
%dev.quarkus.hibernate-orm.schema-management.strategy=update
%dev.quarkus.datasource.reactive.url=postgresql://localhost:5432/iot

# ORM BATCHING
quarkus.hibernate-orm.jdbc.statement-batch-size=50
quarkus.hibernate-orm.jdbc.order-inserts=true
quarkus.hibernate-orm.jdbc.order-updates=true
quarkus.hibernate-orm.fetch.batch-size=20

# LOGGING
# TODO
quarkus.otel.logs.exporter=none
quarkus.hibernate-orm.log.sql=false
