quarkus.http.port=8083

# DATABASE
quarkus.datasource.db-kind=PostgreSQL

%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=postgres
%dev.quarkus.datasource.reactive.url=postgresql://localhost:5432/iot

# KAFKA/REDPANDA MESSAGING
kafka.bootstrap.servers=localhost:19092

mp.messaging.incoming.power-in.connector=smallrye-kafka
mp.messaging.incoming.power-in.topic=power-consumption-events
mp.messaging.incoming.power-in.group.id=main-service-group
mp.messaging.incoming.power-in.value.deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
mp.messaging.incoming.power-in.specific.protobuf.value.type=dev.nez.proto.timeddata.PowerConsumptionData
mp.messaging.incoming.power-in.schema.registry.url=http://localhost:18091

# LOGGING
# quarkus.log.level=DEBUG
quarkus.hibernate-orm.log.sql=false
