%dev.quarkus.http.port=8083

quarkus.config.locations=${SECRETS_DIR:../secrets}/admin/credentials.properties

# DATABASE
quarkus.datasource.db-kind=PostgreSQL
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}

quarkus.datasource.reactive.statement-cache-max-size=1024
quarkus.datasource.reactive.max-size=20

%dev.quarkus.datasource.reactive.url=postgresql://localhost:5432/iot
%prod.quarkus.datasource.reactive.url=postgresql://host.docker.internal:5432/iot

# ========================================
# KAFKA/REDPANDA MESSAGING
# ========================================
kafka.bootstrap.servers=host.docker.internal:19092
# 1 day
RETENTION_MS=864000000
# 256 MB
RETENTION_BYTES=268435456

mp.messaging.incoming.power-in.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
mp.messaging.incoming.smoke-in.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
mp.messaging.incoming.air-in.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
mp.messaging.incoming.batt-in.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
mp.messaging.incoming.temp-in.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer

kafka.group.id=main-service-group

mp.messaging.incoming.power-in.connector=smallrye-kafka
mp.messaging.incoming.power-in.topic=power-consumption-events
mp.messaging.incoming.power-in.value.deserializer=dev.nez.consumer.deserealizer.PowerConsumptionDeserializer
mp.messaging.incoming.power-in.batch=true
mp.messaging.incoming.power-in.max.poll.records=4096
mp.messaging.incoming.power-in.fetch.min.bytes=16384
mp.messaging.incoming.power-in.fetch.max.wait.ms=20
mp.messaging.incoming.power-in.concurrency=8

kafka.topic.power-consumption-events.retention.ms=${RETENTION_MS}
kafka.topic.power-consumption-events.retention.bytes=${RETENTION_BYTES}

mp.messaging.incoming.smoke-in.connector=smallrye-kafka
mp.messaging.incoming.smoke-in.topic=smoke-consumption-events
mp.messaging.incoming.smoke-in.value.deserializer=dev.nez.consumer.deserealizer.SmokeDetectorDeserializer
mp.messaging.incoming.smoke-in.batch=true
mp.messaging.incoming.smoke-in.max.poll.records=4096
mp.messaging.incoming.smoke-in.fetch.min.bytes=16384
mp.messaging.incoming.smoke-in.fetch.max.wait.ms=20

kafka.topic.smoke-consumption-events.retention.ms=${RETENTION_MS}
kafka.topic.smoke-consumption-events.retention.bytes=${RETENTION_BYTES}

mp.messaging.incoming.air-in.connector=smallrye-kafka
mp.messaging.incoming.air-in.topic=air-consumption-events
mp.messaging.incoming.air-in.value.deserializer=dev.nez.consumer.deserealizer.AirQualityDeserializer
mp.messaging.incoming.air-in.batch=true
mp.messaging.incoming.air-in.max.poll.records=4096
mp.messaging.incoming.air-in.fetch.min.bytes=16384
mp.messaging.incoming.air-in.fetch.max.wait.ms=20

kafka.topic.air-consumption-events.retention.ms=${RETENTION_MS}
kafka.topic.air-consumption-events.retention.bytes=${RETENTION_BYTES}

mp.messaging.incoming.batt-in.connector=smallrye-kafka
mp.messaging.incoming.batt-in.topic=batt-consumption-events
mp.messaging.incoming.batt-in.value.deserializer=dev.nez.consumer.deserealizer.BatteryDataDeserializer
mp.messaging.incoming.batt-in.batch=true
mp.messaging.incoming.batt-in.max.poll.records=4096
mp.messaging.incoming.batt-in.fetch.min.bytes=16384
mp.messaging.incoming.batt-in.fetch.max.wait.ms=20

kafka.topic.batt-consumption-events.retention.ms=${RETENTION_MS}
kafka.topic.batt-consumption-events.retention.bytes=${RETENTION_BYTES}

mp.messaging.incoming.temp-in.connector=smallrye-kafka
mp.messaging.incoming.temp-in.topic=temp-consumption-events
mp.messaging.incoming.temp-in.value.deserializer=dev.nez.consumer.deserealizer.TemperatureDeserializer
mp.messaging.incoming.temp-in.batch=true
mp.messaging.incoming.temp-in.max.poll.records=4096
mp.messaging.incoming.temp-in.fetch.min.bytes=16384
mp.messaging.incoming.temp-in.fetch.max.wait.ms=20

kafka.topic.temp-consumption-events.retention.ms=${RETENTION_MS}
kafka.topic.temp-consumption-events.retention.bytes=${RETENTION_BYTES}

# ========================================
# OPENTELEMETRY
# ========================================

quarkus.otel.exporter.otlp.endpoint=http://host.docker.internal:4317

# METRICS
smallrye.messaging.observation.enabled=true
quarkus.otel.metrics.enabled=true
quarkus.micrometer.binder.kafka.enabled=true
quarkus.otel.metric.export.interval=10s

# LOGGING
quarkus.otel.logs.enabled=true

# TRACES
quarkus.otel.bsp.schedule.delay=10s
quarkus.otel.traces.sampler=parentbased_traceidratio
quarkus.otel.traces.sampler.arg=0.1