%dev.quarkus.http.port=8083
quarkus.config.locations=${SECRETS_DIR:../secrets}/admin/credentials.properties

# DATABASE
quarkus.datasource.db-kind=PostgreSQL
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}

quarkus.datasource.reactive.statement-cache-max-size=256
quarkus.datasource.reactive.max-size=40
quarkus.hibernate-orm.jdbc.statement-batch-size=1024
quarkus.hibernate-orm.jdbc.order-inserts=true
quarkus.hibernate-orm.jdbc.order-updates=true

%dev.quarkus.hibernate-orm.schema-management.strategy=none
%dev.quarkus.datasource.reactive.url=postgresql://localhost:5432/iot
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/iot

quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.migrate-at-start=true
%dev.quarkus.flyway.clean-at-start=true

# KAFKA/REDPANDA MESSAGING
kafka.bootstrap.servers=localhost:19092
# 1 day
RETENION_MS=864000000
# 1 GB
RETENION_BYTES=1073741824

mp.messaging.incoming.power-in.connector=smallrye-kafka
mp.messaging.incoming.power-in.topic=power-consumption-events
mp.messaging.incoming.power-in.group.id=main-service-group
mp.messaging.incoming.power-in.value.deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
mp.messaging.incoming.power-in.specific.protobuf.value.type=dev.nez.dto.proto.timeddata.PowerConsumptionData
mp.messaging.incoming.power-in.schema.registry.url=http://localhost:18091
mp.messaging.incoming.power-in.batch=true
mp.messaging.incoming.power-in.max.poll.records=2048
mp.messaging.incoming.power-in.fetch.max.wait.ms=100
kafka.topic.power-consumption-events.retention.ms=${RETENION_MS}
kafka.topic.power-consumption-events.retention.bytes=${RETENION_BYTES}

mp.messaging.incoming.smoke-in.connector=smallrye-kafka
mp.messaging.incoming.smoke-in.topic=smoke-consumption-events
mp.messaging.incoming.smoke-in.group.id=main-service-group
mp.messaging.incoming.smoke-in.value.deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
mp.messaging.incoming.smoke-in.specific.protobuf.value.type=dev.nez.dto.proto.timeddata.SmokeDetectorData
mp.messaging.incoming.smoke-in.schema.registry.url=http://localhost:18091
mp.messaging.incoming.smoke-in.batch=true
mp.messaging.incoming.smoke-in.max.poll.records=64
mp.messaging.incoming.smoke-in.fetch.max.wait.ms=10
kafka.topic.smoke-consumption-events.retention.ms=${RETENION_MS}
kafka.topic.smoke-consumption-events.retention.bytes=${RETENION_BYTES}

mp.messaging.incoming.air-in.connector=smallrye-kafka
mp.messaging.incoming.air-in.topic=air-consumption-events
mp.messaging.incoming.air-in.group.id=main-service-group
mp.messaging.incoming.air-in.value.deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
mp.messaging.incoming.air-in.specific.protobuf.value.type=dev.nez.dto.proto.timeddata.AirQualityData
mp.messaging.incoming.air-in.schema.registry.url=http://localhost:18091
mp.messaging.incoming.air-in.batch=true
mp.messaging.incoming.air-in.max.poll.records=512
mp.messaging.incoming.air-in.fetch.max.wait.ms=100
kafka.topic.air-consumption-events.retention.ms=${RETENION_MS}
kafka.topic.air-consumption-events.retention.bytes=${RETENION_BYTES}

mp.messaging.incoming.batt-in.connector=smallrye-kafka
mp.messaging.incoming.batt-in.topic=batt-consumption-events
mp.messaging.incoming.batt-in.group.id=main-service-group
mp.messaging.incoming.batt-in.value.deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
mp.messaging.incoming.batt-in.specific.protobuf.value.type=dev.nez.dto.proto.timeddata.BatteryData
mp.messaging.incoming.batt-in.schema.registry.url=http://localhost:18091
mp.messaging.incoming.batt-in.batch=true
mp.messaging.incoming.batt-in.max.poll.records=128
mp.messaging.incoming.batt-in.fetch.max.wait.ms=100
kafka.topic.batt-consumption-events.retention.ms=${RETENION_MS}
kafka.topic.batt-consumption-events.retention.bytes=${RETENION_BYTES}

# ========================================
# OPENTELEMETRY
# ========================================

quarkus.otel.exporter.otlp.endpoint=http://localhost:4317

# METRICS
smallrye.messaging.observation.enabled=true
quarkus.otel.metrics.enabled=true
quarkus.micrometer.binder.kafka.enabled=true
quarkus.otel.metric.export.interval=10s

# LOGGING
quarkus.hibernate-orm.log.sql=false
quarkus.log.console.json.enabled=false
quarkus.otel.logs.enabled=true

quarkus.log.category."org.flywaydb".level=WARN

# TODO
quarkus.otel.traces.exporter=none