quarkus.rest-client.auth-api.url=http://localhost:8080
mqtt.broker.host=localhost
mqtt.broker.port=1882

%prod.quarkus.rest-client.auth-api.url=http://host.docker.internal:8080
%prod.mqtt.broker.host=host.docker.internal

# TLS
mqtt.broker.ca-path=${SECRETS_DIR:../secrets}/tls/ca.crt