quarkus.http.port=8084

# MQTT
mqtt.broker.host = localhost
mqtt.broker.port = 1882
%prod.mqtt.broker.host = host.docker.internal

# REST
quarkus.rest-client.auth-api.url = http://localhost:8081
%prod.quarkus.rest-client.auth-api.url = http://host.docker.internal:8081
quarkus.rest-client.auth-api.read-timeout=15000

quarkus.rest-client.edge-api.url = http://localhost:8082

# BASIC AUTH
quarkus.http.auth.basic=true

quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.admin=admin
quarkus.security.users.embedded.roles.admin=admin

# TLS
mqtt.broker.ca-path = ${SECRETS_DIR:../secrets}/tls/ca.crt

# GENERATE SETTINGS
gen.air.proto.count = 1
gen.air.proto.topic = dev/air/p
gen.air.json.count = 1
gen.air.json.topic = dev/air/j

gen.power.proto.count = 1
gen.power.proto.topic = dev/power/p
gen.power.json.count = 1
gen.power.json.topic = dev/power/j

gen.smoke.proto.count = 1
gen.smoke.proto.topic = dev/smoke/p
gen.smoke.json.count = 1
gen.smoke.json.topic = dev/smoke/j

gen.battery.proto.topic = dev/batt/p
gen.battery.json.topic = dev/batt/j

# LOGGING
# quarkus.log.level=DEBUG
