quarkus.rest-client.auth-api.url = http://localhost:8081
mqtt.broker.host = localhost
mqtt.broker.port = 1882

%prod.quarkus.rest-client.auth-api.url = http://host.docker.internal:8081
%prod.mqtt.broker.host = host.docker.internal

# TLS
mqtt.broker.ca-path = ${SECRETS_DIR:../secrets}/tls/ca.crt

# GENERATE SETTINGS
gen.air.proto.count = 1
gen.air.proto.topic = dev/air/p
gen.air.json.count = 1
gen.air.json.topic = dev/air/j

gen.power.proto.count = 2500
gen.power.proto.topic = dev/power/p
gen.power.json.count = 2500
gen.power.json.topic = dev/power/j

gen.smoke.proto.count = 1
gen.smoke.proto.topic = dev/smoke/p
gen.smoke.json.count = 1
gen.smoke.json.topic = dev/smoke/j

gen.battery.proto.topic = dev/batt/p
gen.battery.json.topic = dev/batt/j

# LOGGING
# quarkus.log.level=DEBUG
