{
 "title": "BaseDashboard",
 "time": { "from": "2026-05-16T18:02:21.119Z", "to": "2026-05-16T18:04:07.482Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "edge_channel_in",
    "query": {
     "query": "label_values(quarkus_messaging_message_count_total{job=\"edge-service\"},channel)"
    }
   },
   {
    "name": "edge_channel_out",
    "query": {
     "query": "label_values(quarkus_messaging_message_count_total{job=\"edge-service\"},channel)"
    }
   },
   {
    "name": "main_channel_in",
    "query": {
     "query": "label_values(quarkus_messaging_message_count_total{job=\"main-service\"},channel)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Received messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(broker_publish_messages_received[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total process delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, sum by(le) (rate(message_delay_milliseconds_bucket[30s]))))\r\n+ on() \r\n(sum(broker_messages_stored - 53) / sum(rate(broker_publish_messages_sent[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total services memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{job=\"auth-service\"})\r\n+\r\nsum by (instance) (jvm_memory_used_bytes{job=\"edge-service\"})\r\n+\r\nsum by (instance) (jvm_memory_used_bytes{job=\"main-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Auth-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance) (increase(http_server_requests_milliseconds_count{job=\"auth-service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance) (increase(postgresql_processing_milliseconds_count{job=\"auth-service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{job=\"auth-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Edge-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Consume Rate from MQTT broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(quarkus_messaging_message_count_total{job=\"edge-service\", channel=~\"${edge_channel_in}\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce Rate to MQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(quarkus_messaging_message_count_total{job=\"edge-service\",channel=~\"${edge_channel_out}\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{job=\"edge-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Main-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Consume Rate from MQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(quarkus_messaging_message_count_total{job=\"main-service\", channel=~\"${main_channel_in}.*\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(message_delay_milliseconds_count{job=\"main-service\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{job=\"main-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Analitycs-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{job=\"analytics-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redpanda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Write latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(vectorized_kafka_latency_produce_latency_us_bucket[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(vectorized_kafka_latency_fetch_latency_us_bucket[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current disk usage vs target",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (instance) (vectorized_space_management_disk_usage_bytes) \r\n  / \r\n  sum by (instance) (vectorized_space_management_target_disk_size_bytes)\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unprocessed Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "avg_over_time((sum(vectorized_cluster_partition_end_offset) - sum(vectorized_cluster_partition_committed_offset))[20s:10s])\r\n#sum(vectorized_cluster_partition_end_offset) - sum(vectorized_cluster_partition_committed_offset)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "expr": "sum(vectorized_kafka_rpc_active_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TimescaleDB (Postgres)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Total write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{datname=\"iot\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"iot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"iot\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{datname=\"iot\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{datname=\"iot\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "targets": [
    { "expr": "sum(pg_locks_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks{datname=\"iot\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MQTT broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(broker_publish_messages_received[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(broker_publish_messages_sent[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unprocessed Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "targets": [
    { "expr": "broker_messages_stored", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Clients connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "targets": [
    { "expr": "broker_clients_connected", "legendFormat": "__auto" }
   ]
  }
 ]
}