{
 "title": "LogsDashboard",
 "time": { "from": "2026-05-05T13:59:38.037Z", "to": "2026-05-05T15:59:38.037Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {}
   },
   {
    "name": "level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Log volume by level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({exporter=\"OTLP\", service_name=~\"$service\"}[$__interval]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Logs Processed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({exporter=\"OTLP\", service_name=~\"$service\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({exporter=\"OTLP\", service_name=~\"$service\", level=\"ERROR\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Service logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=~\"${service:regex}\"} \r\n  | json \r\n  | severity=~\"(?i)${level:regex}\"\r\n  | line_format \"[{{.attributes_bridge_name}}] ({{.attributes_thread_name}}) {{.body}}\"\r\n"
    }
   ]
  }
 ]
}