quarkus.devservices.enabled=false

quarkus.http.ssl-port=8086
quarkus.config.locations=${SECRETS_DIR:../config}/secrets/admin/credentials.properties

# =======================================
# REST
# =======================================
quarkus.http.ssl.certificate.files=${SECRETS_DIR:../config}/secrets/tls/server.crt
quarkus.http.ssl.certificate.key-files=${SECRETS_DIR:../config}/secrets/tls/server.key
quarkus.http.insecure-requests=disabled

quarkus.rest-client.producer-api.url = http://localhost:8084
%prod.quarkus.rest-client.producer-api.url = http://host.docker.internal:8084

# ========================================
# Basic Auth
# ========================================
quarkus.http.auth.basic=true

# ========================================
# Quinoa
# ========================================
quarkus.quinoa.ui-dir=src/main/webui
quarkus.quinoa.build-dir=dist
quarkus.quinoa.dev-server.port=5173

quarkus.quinoa.ignored-path-prefixes=/api
quarkus.quinoa.enable-spa-routing=true

quarkus.quinoa.package-manager-install=true
quarkus.quinoa.package-manager-install.node-version=26.2.0

# ========================================
# DATABASE
# ========================================
quarkus.datasource.db-kind=PostgreSQL
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.reactive.statement-cache-max-size=4096

quarkus.hibernate-orm.schema-management.strategy=none

%dev.quarkus.datasource.reactive.url=postgresql://localhost:5432/iot
%prod.quarkus.datasource.reactive.url=postgresql://host.docker.internal:5432/iot

# ========================================
# KAFKA/REDPANDA MESSAGING
# ========================================
kafka.bootstrap.servers=host.docker.internal:19092
kafka.group.id=monitor-service-group
kafka.producer.batch.size=65536
kafka.producer.linger.ms=10
kafka.producer.max.in.flight.requests.per.connection=100

mp.messaging.incoming.power-consumption.connector=smallrye-kafka
mp.messaging.incoming.power-consumption.topic=power-consumption-events
mp.messaging.incoming.power-consumption.value.deserializer=dev.nez.monitoring.model.deserealizer.PowerConsumptionDeserializer

mp.messaging.incoming.air-quality.connector=smallrye-kafka
mp.messaging.incoming.air-quality.topic=air-consumption-events
mp.messaging.incoming.air-quality.value.deserializer=dev.nez.monitoring.model.deserealizer.AirQualityDeserializer

mp.messaging.incoming.smoke-detector.connector=smallrye-kafka
mp.messaging.incoming.smoke-detector.topic=smoke-consumption-events
mp.messaging.incoming.smoke-detector.value.deserializer=dev.nez.monitoring.model.deserealizer.SmokeDetectorDeserializer

mp.messaging.incoming.battery.connector=smallrye-kafka
mp.messaging.incoming.battery.topic=batt-consumption-events
mp.messaging.incoming.battery.value.deserializer=dev.nez.monitoring.model.deserealizer.BatteryDataDeserializer

mp.messaging.incoming.temperature.connector=smallrye-kafka
mp.messaging.incoming.temperature.topic=temp-consumption-events
mp.messaging.incoming.temperature.value.deserializer=dev.nez.monitoring.model.deserealizer.TemperatureDeserializer

mp.messaging.incoming.power-consumption.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
mp.messaging.incoming.air-quality.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
mp.messaging.incoming.smoke-detector.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
mp.messaging.incoming.battery.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
mp.messaging.incoming.temperature.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer

# KAFKA THRESHOLDS

# --- Air Quality ---
mp.messaging.outgoing.air-thresholds-out.connector=smallrye-kafka
mp.messaging.outgoing.air-thresholds-out.topic=air-thresholds-topic
mp.messaging.outgoing.air-thresholds-out.key.serializer=org.apache.kafka.common.serialization.LongSerializer
mp.messaging.outgoing.air-thresholds-out.value.serializer=dev.nez.configuration.dto.JsonSerializer

# --- Battery ---
mp.messaging.outgoing.battery-thresholds-out.connector=smallrye-kafka
mp.messaging.outgoing.battery-thresholds-out.topic=batt-thresholds-topic
mp.messaging.outgoing.battery-thresholds-out.key.serializer=org.apache.kafka.common.serialization.LongSerializer
mp.messaging.outgoing.battery-thresholds-out.value.serializer=dev.nez.configuration.dto.JsonSerializer

# --- Power ---
mp.messaging.outgoing.power-thresholds-out.connector=smallrye-kafka
mp.messaging.outgoing.power-thresholds-out.topic=power-thresholds-topic
mp.messaging.outgoing.power-thresholds-out.key.serializer=org.apache.kafka.common.serialization.LongSerializer
mp.messaging.outgoing.power-thresholds-out.value.serializer=dev.nez.configuration.dto.JsonSerializer

# --- Smoke ---
mp.messaging.outgoing.smoke-thresholds-out.connector=smallrye-kafka
mp.messaging.outgoing.smoke-thresholds-out.topic=smoke-thresholds-topic
mp.messaging.outgoing.smoke-thresholds-out.key.serializer=org.apache.kafka.common.serialization.LongSerializer
mp.messaging.outgoing.smoke-thresholds-out.value.serializer=dev.nez.configuration.dto.JsonSerializer

# --- Temperature ---
mp.messaging.outgoing.temperature-thresholds-out.connector=smallrye-kafka
mp.messaging.outgoing.temperature-thresholds-out.topic=temp-thresholds-topic
mp.messaging.outgoing.temperature-thresholds-out.key.serializer=org.apache.kafka.common.serialization.LongSerializer
mp.messaging.outgoing.temperature-thresholds-out.value.serializer=dev.nez.configuration.dto.JsonSerializer

# EDGE CONFIG
mp.messaging.outgoing.filter-config-out.connector=smallrye-kafka
mp.messaging.outgoing.filter-config-out.topic=filter-config-topic
mp.messaging.outgoing.filter-config-out.value.serializer=dev.nez.configuration.dto.JsonSerializer

# ========================================
# OPENTELEMETRY
# ========================================
quarkus.otel.exporter.otlp.endpoint=http://host.docker.internal:4317

# METRICS
smallrye.messaging.observation.enabled=true
quarkus.otel.metrics.enabled=true
quarkus.micrometer.binder.kafka.enabled=true
quarkus.otel.metric.export.interval=10s

# LOGGING
quarkus.otel.logs.enabled=true

# TRACES
quarkus.otel.traces.enabled=false
#quarkus.otel.bsp.schedule.delay=10s
#quarkus.otel.traces.sampler=parentbased_traceidratio
#quarkus.otel.traces.sampler.arg=0.1