quarkus.http.port=8082

# METRICS
quarkus.otel.metrics.enabled=true
quarkus.otel.exporter.otlp.metrics.endpoint=http://localhost:4317/v1/metrics
quarkus.otel.metric.export.interval=30s
# TODO
quarkus.otel.logs.exporter=none

# MQTT MESSAGING
mp.messaging.connector.mqtt-hivemq.auto-clean-session=false
mp.messaging.connector.mqtt-hivemq.buffer-size=100
mp.messaging.connector.mqtt-hivemq.qos=1
mp.messaging.connector.mqtt-hivemq.client-id=edge-consumer


mp.messaging.incoming.power-p-in.connector=mqtt-hivemq
mp.messaging.incoming.power-p-in.host=localhost
mp.messaging.incoming.power-p-in.port=1883
mp.messaging.incoming.power-p-in.topic=dev/power/p

mp.messaging.incoming.air-j-in.connector=mqtt-hivemq
mp.messaging.incoming.air-j-in.host=localhost
mp.messaging.incoming.air-j-in.port=1883
mp.messaging.incoming.air-j-in.topic=dev/air/j

mp.messaging.incoming.air-p-in.connector=mqtt-hivemq
mp.messaging.incoming.air-p-in.host=localhost
mp.messaging.incoming.air-p-in.port=1883
mp.messaging.incoming.air-p-in.topic=dev/air/p

mp.messaging.incoming.batt-j-in.connector=mqtt-hivemq
mp.messaging.incoming.batt-j-in.host=localhost
mp.messaging.incoming.batt-j-in.port=1883
mp.messaging.incoming.batt-j-in.topic=dev/batt/j

mp.messaging.incoming.batt-p-in.connector=mqtt-hivemq
mp.messaging.incoming.batt-p-in.host=localhost
mp.messaging.incoming.batt-p-in.port=1883
mp.messaging.incoming.batt-p-in.topic=dev/batt/p

## KAFKA/REDPANDA MESSAGING
#kafka.bootstrap.servers=localhost:19092

# LOGGING
# quarkus.log.level=DEBUG