pid_file /tmp/mosquitto.pid
per_listener_settings true

persistence true
persistence_location /mosquitto/data/

max_queued_messages 50000
max_queued_bytes 1073741824

max_inflight_messages 10

# ==========================================
# LOGS
# ==========================================

#log_dest stdout
#log_type all

log_dest stdout
log_type error
log_type warning
log_type notice

persistent_client_expiration 1d

# ==========================================
# PORT 1882 - IoT DEVICES (JWT Auth + ACL)
# ==========================================
listener 1882
allow_anonymous false

plugin /usr/lib/libmosquitto_jwt_auth.so
auth_opt_jwt_alg ES256
auth_opt_jwt_jwks_file /etc/mosquitto/certs/jwks.json

auth_opt_jwt_validate_sub_match_username true

# --- TLS ---
cafile /etc/mosquitto/certs/tls/ca.crt
certfile /etc/mosquitto/certs/tls/server.crt
keyfile /etc/mosquitto/certs/tls/server.key

# ==========================================
# PORT 1883 - INTERNAL (Quarkus EDGE Service)
# ==========================================
listener 1883 0.0.0.0
allow_anonymous true