version: '3.8'
services:

  mosquitto:
    build:
      context: ../mosquitto
      dockerfile: .dockerfile
    container_name: iot_mosquitto
    ports:
      - "1882:1882"
      - "1883:1883"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ../mosquitto/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ../secrets/jwks.json:/etc/mosquitto/certs/jwks.json:ro
    networks:
      - iot_network
    tty: true
    stdin_open: true
    command: mosquitto -c /etc/mosquitto/mosquitto.conf

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    command: start-dev
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "1884:1884"
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: iot_timescaledb
    environment:
      POSTGRES_DB: iot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data:

networks:
  iot_network:
    driver: bridge