version: '3.8'
name: monitoring-local
services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ../monitoring/prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver' # Allows to receive data from Alloy

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ../monitoring/tempo-config/tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - "3200:3200"   # HTTP
      - "9095:9095"   # Internal gRPC
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: grafana-alloy
    user: root
    ports:
      - "12345:12345"
      - "4317:4317"   # OTLP gRPC receive
      - "4318:4318"   # OTLP HTTP receive
      - "1514:1514"
    restart: unless-stopped
    volumes:
      - ../monitoring/alloy-config/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - ../secrets/admin/credentials.properties
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
      - tempo
    volumes:
      - ../monitoring/grafana-config/provisioning:/etc/grafana/provisioning