version: '3.8'
name: services

services:
  device-service:
    image: quarkus/device-service-native:latest
    container_name: device-service-app
    ports:
      - "8081:8081"
    volumes:
      - ../config/secrets/admin/credentials.properties:/config/secrets/admin/credentials.properties:ro
      - ../config/secrets/jwt:/config/secrets/jwt:ro
      - ../config/secrets/tls:/config/secrets/tls:ro
    environment:
      - QUARKUS_PROFILE=prod
      - CONF_DIR=/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  edge-service:
    image: quarkus/edge-service-native:latest
    container_name: edge-service-app
    ports:
      - "8082:8082"
    volumes:
      - ../config/secrets/admin/credentials.properties:/config/secrets/admin/credentials.properties:ro
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:19092
      - MP_MESSAGING_CONNECTOR_SMALLRYE_MQTT_HIVEMQ_HOST=host.docker.internal
      - QUARKUS_PROFILE=prod
      - CONF_DIR=/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  consumer-service:
    image: quarkus/consumer-service-native:latest
    container_name: consumer-service-app
    ports:
      - "8083:8083"
    volumes:
      - ../config/secrets/admin/credentials.properties:/config/secrets/admin/credentials.properties:ro
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:19092
      - QUARKUS_PROFILE=prod
      - CONF_DIR=/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  analytics-service:
    image: quarkus/analytics-service-native:latest
    container_name: analytics-service-app
    ports:
      - "8085:8085"
    volumes:
      - ../config/secrets/telegram/telegram.properties:/config/secrets/telegram/telegram.properties:ro
    environment:
      - QUARKUS_PROFILE=prod
      - CONF_DIR=/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  monitor-service:
    image: quarkus/monitor-service-native:latest
    container_name: monitor-service-app
    ports:
      - "8086:8086"
    volumes:
      - ../config/secrets/admin/credentials.properties:/config/secrets/admin/credentials.properties:ro
      - ../config/secrets/tls:/config/secrets/tls:ro
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:19092
      - QUARKUS_PROFILE=prod
      - CONF_DIR=/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  producer-service:
    image: quarkus/producer-service-native:latest
    container_name: producer-service-app
    ports:
      - "8084:8084"
    volumes:
      - ../config/secrets/admin/credentials.properties:/config/secrets/admin/credentials.properties:ro
      - ../config/secrets/jwt:/secrets/jwt:ro
      - ../config/secrets/tls:/secrets/tls:ro
    environment:
      - QUARKUS_PROFILE=prod
      - CONF_DIR=/config
    depends_on:
      - device-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped