version: '3.8'
name: redpanda-local
services:

  redpanda:
    build: ../redpanda
    image: configured-redpanda:local
    container_name: redpanda-0
    restart: unless-stopped
    ports:
      - 18091:8091  # Schema Registry
      - 18092:8092  # HTTP Proxy
      - 19092:19092 # Kafka API
      - 19644:9644  # Admin API
    volumes:
      - redpanda-data:/var/lib/redpanda/data
#    volumes:
#      - type: tmpfs
#        target: /var/lib/redpanda/data
#        tmpfs:
#          size: 2073741824
#          mode: 0777
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://host.docker.internal:19092

  redpanda-init:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda-init
    depends_on:
      - redpanda
    entrypoint: [ "" ]
    command:
      - sh
      - -c
      - |
        echo "Waiting for Redpanda to be ready..."
        until rpk cluster info --brokers redpanda-0:9092; do sleep 1; done
        
        echo "Creating topics..."
        
        rpk --brokers redpanda-0:9092 topic create power-consumption-events -p 8 --topic-config cleanup.policy=delete --topic-config retention.bytes=268435456 --topic-config segment.bytes=67108864 || true
        
        rpk --brokers redpanda-0:9092 topic create smoke-consumption-events -p 1 --topic-config cleanup.policy=delete --topic-config retention.bytes=67108864 --topic-config segment.bytes=16777216 || true
        
        rpk --brokers redpanda-0:9092 topic create air-consumption-events -p 1 --topic-config cleanup.policy=delete --topic-config retention.bytes=67108864 --topic-config segment.bytes=16777216 || true
        
        rpk --brokers redpanda-0:9092 topic create batt-consumption-events -p 1 --topic-config cleanup.policy=delete --topic-config retention.bytes=67108864 --topic-config segment.bytes=16777216 || true
        
        echo "Infrastructure ready."

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    entrypoint: /app/console
    command: --config.filepath=/console-config.yml
    restart: unless-stopped
    ports:
      - 8099:8080
    volumes:
      - ../redpanda/console-config.yml:/console-config.yml
    depends_on:
      - redpanda

volumes:
  redpanda-data:
    driver: local