version: '3.8'
name: infra-local
services:

  mosquitto:
    build:
      context: ../mosquitto
      dockerfile: .dockerfile
    container_name: iot_mosquitto
    ports:
      - "1882:1882"
      - "1883:1883"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ../mosquitto/mosquitto.conf:/etc/mosquitto/mosquitto.conf:ro
      - ../secrets/jwt/jwks.json:/etc/mosquitto/certs/jwks.json:ro
      # --- TLS ---
      - ../secrets/tls/ca.crt:/etc/mosquitto/certs/tls/ca.crt:ro
      - ../secrets/tls/server.crt:/etc/mosquitto/certs/tls/server.crt:ro
      - ../secrets/tls/server.key:/etc/mosquitto/certs/tls/server.key:ro
    networks:
      - iot_network
    tty: false # true -- for instantly output
    stdin_open: true
    command: mosquitto -c /etc/mosquitto/mosquitto.conf

#  keycloak:
#    image: quay.io/keycloak/keycloak:26.5.0
#    command: start-dev
#    environment:
#      KC_DB: dev-file
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    ports:
#      - "1884:1884"
#    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg18
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '3G'
    container_name: iot_timescaledb
    env_file:
      - ../secrets/admin/credentials.properties
    environment:
      POSTGRES_DB: iot
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=300"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "checkpoint_timeout=15min"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "min_wal_size=1GB"

volumes:
  timescaledb_data:

networks:
  iot_network:
    driver: bridge