{
 "title": "BaseDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "edge_channel_in",
    "query": {
     "query": "label_values(quarkus_messaging_message_count_total{job=\"edge-service\"},channel)"
    }
   },
   {
    "name": "edge_channel_out",
    "query": {
     "query": "label_values(quarkus_messaging_message_count_total{job=\"edge-service\"},channel)"
    }
   },
   {
    "name": "consumer_channel_in",
    "query": {
     "query": "label_values(quarkus_messaging_message_count_total{job=\"consumer-service\"},channel)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Received messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(broker_publish_messages_received[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total process delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, sum by(le) (rate(message_delay_milliseconds_bucket[30s]))))\r\n+ on() \r\n(sum(broker_messages_stored - 54) / sum(rate(broker_publish_messages_sent[30s])) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (broker_load_bytes_received_1min)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total services memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Device-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (instance) (increase(http_server_requests_milliseconds_count{job=\"device-service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum by (instance) (increase(postgresql_processing_milliseconds_count{job=\"device-service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{job=\"device-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Edge-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Consume Rate from MQTT broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(quarkus_messaging_message_count_total{job=\"edge-service\", channel=~\"${edge_channel_in}\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce Rate to MQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(quarkus_messaging_message_count_total{job=\"edge-service\",channel=~\"${edge_channel_out}\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{job=\"edge-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consumer-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Consume Rate from MQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "batch/sec" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(quarkus_messaging_message_count_total{job=\"consumer-service\", channel=~\"${consumer_channel_in}.*\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(message_delay_milliseconds_count{job=\"consumer-service\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{job=\"consumer-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Analitycs-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Service Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_thread_process_total{thread_id=~\"^analytics-service.*\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analityc delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_stream_processor_node_record_e2e_latency_avg{thread_id=~\"^analytics-service.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{job=\"analytics-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redpanda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Write latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(vectorized_kafka_latency_produce_latency_us_bucket[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(vectorized_kafka_latency_fetch_latency_us_bucket[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current disk usage vs target",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (instance) (vectorized_space_management_disk_usage_bytes) \r\n  / \r\n  sum by (instance) (vectorized_space_management_target_disk_size_bytes)\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unprocessed Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "avg_over_time((sum(vectorized_cluster_partition_end_offset) - sum(vectorized_cluster_partition_committed_offset))[20s:10s])\r\n#sum(vectorized_cluster_partition_end_offset) - sum(vectorized_cluster_partition_committed_offset)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "targets": [
    {
     "expr": "sum(vectorized_kafka_rpc_active_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TimescaleDB (Postgres)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Total write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{datname=\"iot\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"iot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"iot\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{datname=\"iot\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{datname=\"iot\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
   "targets": [
    { "expr": "sum(pg_locks_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks{datname=\"iot\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MQTT broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(broker_publish_messages_received[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(broker_publish_messages_sent[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unprocessed Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "targets": [
    { "expr": "broker_messages_stored - 54", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (broker_load_bytes_received_1min)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (broker_load_bytes_sent_1min)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 104 },
   "targets": [
    { "expr": "broker_clients_connected", "legendFormat": "__auto" }
   ]
  }
 ]
}