quarkus.http.port=8085
quarkus.native.resources.includes=**/*.pem,**/*.crt,**/*.jks
quarkus.config.locations=${SECRETS_DIR:../secrets}/telegram/telegram.properties

# REST
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true

# ========================================
# TELEGRAM
# ========================================
quarkus.rest-client.telegram-api.url=https://api.telegram.org
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.channel.id=${TELEGRAM_CHANNEL_ID}

# ========================================
# KAFKA/REDPANDA MESSAGING
# ========================================
kafka.bootstrap.servers=host.docker.internal:19092

kafka.notifications.topic=notifications-events
kafka.topic.consumption.events=power-consumption-events
kafka.topic.power.thresholds=power-thresholds-topic

#mp.messaging.outgoing.telegram-out.topic=telegram-notifications
#mp.messaging.outgoing.telegram-out.connector=smallrye-kafka
#mp.messaging.outgoing.telegram-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.telegram-in.topic=telegram-notifications
mp.messaging.incoming.telegram-in.connector=smallrye-kafka
mp.messaging.incoming.telegram-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.telegram-in.group.id=telegram-notifier-group
mp.messaging.incoming.telegram-in.max.poll.records=20
mp.messaging.incoming.telegram-in.fetch.max.wait.ms=1000

# ========================================
# KAFKA STREAMS LOGGING TUNING
# ========================================

quarkus.log.category."org.apache.kafka.streams.KafkaStreams".level=INFO

quarkus.log.category."org.apache.kafka.streams.processor.internals.StreamTask".level=WARN
quarkus.log.category."org.apache.kafka.streams.processor.internals.StreamThread".level=WARN
quarkus.log.category."org.apache.kafka.streams.processor.internals.ProcessorStateManager".level=WARN
quarkus.log.category."org.apache.kafka.streams.processor.internals.StoreChangelogReader".level=WARN
quarkus.log.category."org.apache.kafka.streams.state.internals.RocksDBTimestampedStore".level=WARN
quarkus.log.category."org.apache.kafka.streams.processor.internals.StreamsPartitionAssignor".level=WARN
quarkus.log.category."org.apache.kafka.streams.processor.internals.assignment.HighAvailabilityTaskAssignor".level=WARN

# ========================================
# OPENTELEMETRY
# ========================================

quarkus.otel.exporter.otlp.endpoint=http://host.docker.internal:4317

# METRICS
quarkus.otel.metrics.enabled=true
quarkus.otel.metric.export.interval=10s

# LOGGING
quarkus.otel.logs.enabled=true

# TRACES
quarkus.otel.bsp.schedule.delay=10s
quarkus.otel.traces.sampler=parentbased_traceidratio
quarkus.otel.traces.sampler.arg=0.1
