quarkus.http.port=8085
quarkus.native.resources.includes=**/*.pem,**/*.crt,**/*.jks
quarkus.config.locations=${SECRETS_DIR:../config}/secrets/telegram/telegram.properties
quarkus.vertx.prefer-native-transport=false

# REST
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true

# ========================================
# TELEGRAM
# ========================================
telegram.client.use = true

quarkus.rest-client.telegram-api.url=https://api.telegram.org
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.channel.id=${TELEGRAM_CHANNEL_ID}

# ========================================
# KAFKA/REDPANDA MESSAGING
# ========================================
kafka-streams.default.deserialization.exception.handler=org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

kafka.group.id=analytics-service-group
kafka.bootstrap.servers=host.docker.internal:19092

kafka.notifications.topic=notifications-events

kafka.topic.power.events=power-consumption-events
kafka.topic.power.thresholds=power-thresholds-topic

kafka.topic.air.events=air-consumption-events
kafka.topic.air.thresholds=air-thresholds-topic

kafka.topic.battery.events=batt-consumption-events
kafka.topic.battery.thresholds=batt-thresholds-topic

kafka.topic.smoke.events=smoke-consumption-events
kafka.topic.smoke.thresholds=smoke-thresholds-topic

kafka.topic.temp.events=temp-consumption-events
kafka.topic.temp.thresholds=temp-thresholds-topic

mp.messaging.incoming.telegram-in.topic=notifications-events
mp.messaging.incoming.telegram-in.connector=smallrye-kafka
mp.messaging.incoming.telegram-in.group.id=telegram-notifier-group
mp.messaging.incoming.telegram-in.batch=true
mp.messaging.incoming.telegram-in.overflow-buffer-size=10000
mp.messaging.incoming.telegram-in.max.poll.records=2500
mp.messaging.incoming.telegram-in.fetch.max.wait.ms=500

filter.delay.min = 5
filter.notifications-events.threshold=1000

# ========================================
# KAFKA STREAMS
# ========================================
%dev.quarkus.kafka-streams.cleanup.on-start=true
quarkus.log.category."org.apache.kafka.streams.KafkaStreams".level=INFO

quarkus.log.category."org.apache.kafka.streams.processor.internals.StreamTask".level=WARN
quarkus.log.category."org.apache.kafka.streams.processor.internals.StreamThread".level=WARN
quarkus.log.category."org.apache.kafka.streams.processor.internals.ProcessorStateManager".level=WARN
quarkus.log.category."org.apache.kafka.streams.processor.internals.StoreChangelogReader".level=WARN
quarkus.log.category."org.apache.kafka.streams.state.internals.RocksDBTimestampedStore".level=WARN
quarkus.log.category."org.apache.kafka.streams.processor.internals.StreamsPartitionAssignor".level=WARN
quarkus.log.category."org.apache.kafka.streams.processor.internals.assignment.HighAvailabilityTaskAssignor".level=WARN

# ========================================
# OPENTELEMETRY
# ========================================

quarkus.otel.exporter.otlp.endpoint=http://host.docker.internal:4317

# METRICS
quarkus.otel.metrics.enabled=true
quarkus.otel.metric.export.interval=10s

# LOGGING
quarkus.otel.logs.enabled=true

# TRACES
quarkus.otel.traces.enabled=false
#quarkus.otel.bsp.schedule.delay=10s
#quarkus.otel.traces.sampler=parentbased_traceidratio
#quarkus.otel.traces.sampler.arg=0.1
