quarkus.http.port=8082

mp.messaging.incoming.telemetry-in.host=localhost
mp.messaging.incoming.telemetry-in.port=1883
mp.messaging.incoming.telemetry-in.connector=smallrye-mqtt-hivemq
mp.messaging.incoming.telemetry-in.topic=dev/temp/j
mp.messaging.incoming.telemetry-in.client-id=edge-consumer-node-1
mp.messaging.incoming.telemetry-in.qos=1
mp.messaging.incoming.telemetry-in.clean-start=false
mp.messaging.incoming.telemetry-in.session-expiry-interval=3600