quarkus.http.ssl-port=8081
quarkus.native.resources.includes=**/*.pem,**/*.crt,**/*.jks

smallrye.jwt.new-token.signature-algorithm=RS256
smallrye.jwt.sign.key.location=file:${SECRETS_DIR:../config}/secrets/jwt/private.pem
quarkus.config.locations=${SECRETS_DIR:../config}/secrets/admin/credentials.properties

jwt.key.id=Hkn7Yqe8yC8XAJHiEJPmDqBqMfoDzPhgid691GNEgSw
auth.jwt.issuer=auth-service

bcrypt.cost = 8

# REST
quarkus.http.ssl.certificate.files=${SECRETS_DIR:../config}/secrets/tls/server.crt
quarkus.http.ssl.certificate.key-files=${SECRETS_DIR:../config}/secrets/tls/server.key
quarkus.http.insecure-requests=disabled

# BASIC AUTH
quarkus.http.auth.basic=true

# DATABASE
quarkus.datasource.db-kind=PostgreSQL
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}

quarkus.datasource.reactive.max-size=40
quarkus.datasource.reactive.statement-cache-max-size=4096

quarkus.hibernate-orm.schema-management.strategy=none

%dev.quarkus.datasource.reactive.url=postgresql://localhost:5432/iot
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/iot

%prod.quarkus.datasource.reactive.url=postgresql://host.docker.internal:5432/iot
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://host.docker.internal:5432/iot

quarkus.hibernate-orm.jdbc.statement-batch-size=128
quarkus.hibernate-orm.fetch.batch-size=128

quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.clean-at-start=true

# ========================================
# OPENTELEMETRY
# ========================================

quarkus.otel.exporter.otlp.endpoint=http://host.docker.internal:4317

# METRICS
quarkus.otel.metrics.enabled=true
quarkus.datasource.metrics.enabled=true
quarkus.otel.metric.export.interval=10s

# LOGGING
quarkus.hibernate-orm.log.sql=false
quarkus.otel.logs.enabled=true

quarkus.log.category."org.flywaydb".level=WARN

# TRACES
quarkus.otel.bsp.schedule.delay=10s
quarkus.otel.traces.sampler=parentbased_traceidratio
quarkus.otel.traces.sampler.arg=0.1
